codecov:
  require_ci_to_pass: true

coverage:
  # range for color spectrum display, red=50%, green=80%
  range: "50...80"
  round: down
  precision: 1

  status:
    project: true
    patch: true
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no